import openpyxl
import shutil
import os


def get_ppe_linecount(FILENAME):
    
    #Gets the total lines so that the get_ppe_actual function can determine where the total is
    
    line_count = 0
    char_count = 0
    with open(FILENAME) as file:
        for line in file:
            line = line.strip("\n")
            line_count += 1
            char_count += len(line)
        return line_count
        
        
def get_ppe_actual(FILENAME):
    
    #Determines where the total is by splitting the string of the last line of the Actuals file
    #from the end of the date on the total line, which happens to be the 135th character on the last line
    #then formats the string, floats it, turns it into a real number, and returns to display on console and
    #write to the excel sheet
    
    line_count = get_ppe_linecount(FILENAME)
    with open(FILENAME) as file:
        file_contents = file.readlines()
        file_total_raw = file_contents[line_count - 1]
        total_actual_str = file_total_raw[135:]
        #total_actual_str = total_actual_str.replace("0", "")
        #the above can't be used accurately if the actual values contain zeros
        total_actual_str = total_actual_str.strip()
        total_actual = float(total_actual_str)
        total_actual = total_actual * 0.00000000001
        total_actual = round(total_actual, 2)
    return total_actual

def write_actual(total_actual):
    
    #opens the excel sheet that is created by the post PPE queries
    #relies on the path that AQT saves query results to, as well as the filename generated by the query
    #writes the total value taken from the UFLACTUALS file saved in the same directory
    
    from openpyxl.styles import Font
    wb = openpyxl.load_workbook(filename='Deferred_Comp_2020-08-06.xlsx', read_only=False)
    sheet = wb.get_sheet_by_name('DEF COMP')
    fontObject = Font(name='MS Sans Serif', size=8)

    sheet['A7'].value = 'TXT File Total'
    sheet['A7'].font = fontObject
    sheet['B7'].value = total_actual
    sheet['B7'].font = fontObject
 
    wb.save('Deferred_Comp_$PPE_Modified.xlsx')


def main():
    os.chdir('H:\SavedQueries')
    # specify file name
    FILENAME = "ACTUAL.txt"
    line_count = get_ppe_linecount(FILENAME)
    total_actual = get_ppe_actual(FILENAME)
    write_actual(total_actual)
    print("Welcome!")
    print()

    print("lines: ", line_count)
    print("Total: ", total_actual)
    


if __name__ == "__main__":
    main()